fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: v4.13.0
    provision: 'https://github.com/puppetlabs/provision.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    mount_iso: 'https://github.com/puppetlabs/puppetlabs-mount_iso.git'
    archive: 'https://github.com/voxpupuli/puppet-archive.git'
  symlinks:
    sqlserver: "#{source_dir}"
