---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  include_todos: true
  profiles:
    strict:
      configs:
        Metrics/LineLength:
          Max: 300
".travis.yml":
  deploy_to_forge:
    enabled: false
  simplecov: true
  notifications:
    slack:
      secure: >-
        NT68BqwAuUSDfmHKZM1Zq7hu2CsK/O2zUhQdeeMBzMWqc6stFdBs8w4zilejzbKJBGSKczV05ctg30e3BfUxGdkuB5kmUCncr5Ky/ygnTi6HnVmdb6ia2Dh41aIoE902SB4h87cOnwcaWAVUBs7lRkJt8j3fK7EZ1egwwzoVaneG/YSMCMniBqSUZFMq5JK76SNBf7VsUzdnxo+nJKJQwMeDQgejb5Fs5F4ua6uSV/keYN7fUjrTLIRA2DKc0nk9fbp8wEN1e12fD0Dziqdlj0jxgJ+8HRAALk82Xu4HivAtOXrGSiXtan2JivbvQW0vFOAd/K1W4ax6ovsZewe4bhMFqgHvdczrlrXFdbKK3cbCJln+StauiWiAVy1wnL2j08zcqxxMPG2HUOpqKjb32CNr+IQZ1GRkx+r62+y18wRb9ir8cTmQli9PcPYFYdM4/5845jaG24qXTQA7s8/f3M7rHgzbZ2ilV6FI76k2iJHX4HAioRW5sD+nIE0STJMnlaVPXmmBhkGwEgoU2Vxbxvas4nCBUikPDoRh5zmY57FaaqJpUEyUgliTWF3OOO8F3xdyv2mdsoMQWi+xBC8CPNOAsTeocYVuZzKOf76eOfwMGcpAp/D8+kAYjb9UFK9tbtil7oeU2hP8kNp+X8AQnM3fxXeGyS1IOeTYAAFfBoI=
appveyor.yml:
  matrix_extras:
  - PUPPET_GEM_VERSION: "~> 6.0"
    RUBY_VERSION: 25
    CHECK: parallel_spec
  - PUPPET_GEM_VERSION: "~> 6.0"
    RUBY_VERSION: 25-x64
    CHECK: parallel_spec
  simplecov: true
Gemfile:
  required:
    ":system_tests":
    - gem: puppet-module-posix-system-r#{minor_version}
      platforms: ruby
    - gem: puppet-module-win-system-r#{minor_version}
      platforms:
      - mswin
      - mingw
      - x64_mingw
    - gem: beaker-testmode_switcher
      version: "~> 0.4"
    - gem: master_manipulator
    - gem: puppet-blacksmith
      version: "~> 3.4"
  optional:
    ":development":
    - gem: ruby-pwsh
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
  spec_overrides:
  - def regexp_matches(available_parameters)
  - "  match(available_parameters)"
  - end
