---
.travis.yml:
  script: "\"bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--color --format documentation'\""
  extras:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="3.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="3.7.0"
CONTRIBUTING.md:
  unmanaged: true
Gemfile:
  supports_windows: true
  required:
    ':development':
      - gem: rake
      - gem: rspec
        version: '~>3.0.0'
      - gem: puppet-lint
      - gem: puppetlabs_spec_helper
        version: '~>0.10.3'
      - gem: puppet_facts
      - gem: mocha
        version: '~>0.10.5'
      - gem: simplecov
      - gem: yard
    ':system_tests':
      - gem: beaker-rspec
      - gem: beaker
      - gem: beaker-puppet_install_helper
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
appveyor.yml:
  matrix_extras:
    - PUPPET_GEM_VERSION: 3.7.0
      RUBY_VER: 193
    - PUPPET_GEM_VERSION: 3.7.0
      RUBY_VER: 200-x64
