version: 1.1.x.{build}
skip_commits:
  message: /(^\(?doc\)?.*|.*[A|a]cceptance [T|t]est.*)/
clone_depth: 10
init:
- SET
- 'mkdir C:\ProgramData\PuppetLabs\code && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\facter && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\hiera && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\puppet\var && exit 0'
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
environment:
  matrix:
  - PUPPET_GEM_VERSION: ~> 4.0
    RUBY_VER: 21-x64
matrix:
  fast_finish: true
install:
- SET PATH=C:\Ruby%RUBY_VER%\bin;%PATH%
- DIR "C:\Ruby%RUBY_VER%\lib\ruby\gems\2.1.0\gems"
- gem -v
- IF NOT EXIST "C:\Ruby%RUBY_VER%\lib\ruby\gems\2.1.0\gems\bundler-1.11.2" gem install bundler --verbose --no-ri --no-rdoc
- DIR "C:\Ruby%RUBY_VER%\lib\ruby\gems\2.1.0\gems"
- bundle install --jobs 4 --retry 2 --without system_tests
- type Gemfile.lock
build: off
test_script:
- bundle exec puppet -V
- ruby -v
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))notifications:
- provider: Email
  to:
  - nobody@nowhere.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
